Youtube clone Homepage
cgcarlosg/YouTube-video-player-clone pull request #1
Opened 2020-09-28 16:27 UTC by cgcarlosg

This is our youtube cloned page which covers embedding videos and images

2020-09-28 16:51 UTC, javitocor requested changes
# STATUS CHANGES REQUIRED ♻️ 

Good job for this your first project, guys! 👍 
Good descriptive commits and clean code! 💯 
The website is almost a copy, and you have shown you can use different methods to positioning elements! 👏 

However, still some changes to do and your project will be approved! 💪 
Do not feel discouraged, we are here to learn and all the changes will make your project look more professional! 🧑‍🎓 

Please, check my comments below 👇 , apply the changes and resubmit your project for a new code review ⏩ 

Good luck, guys! 😃 

- Kindly add the footer, as you can see in the link provided. [here](http://archive.vn/Bss88)
- Please, modify your readme file, it is important to have a professional readme, pay attention to the details, you can follow the guidelines from the pathwright, the live link must be hidden and you should also add your LinkedIn and Twitter or other social media to it:
      - The project has a descriptive README.md ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

- Kindly, use classes instead of Id's, it is a better practice since they are reusable.
- Kindly, add cursor pointer to your links so it looks more like the original.

2020-09-28 16:51 UTC, javitocor commented on README.md
> +https://cgcarlosg.github.io/YouTube-video-player-clone/
here you can use this format: `[live demo link](your link)`

2020-09-28 16:51 UTC, javitocor commented on README.md
> +GitHub: @gango-anan
Add more social media links

2020-09-28 16:51 UTC, javitocor commented on index.html
> +    <section class="main">
you do not need to add an empty div here, you can add a HR tag

2020-09-28 16:51 UTC, javitocor commented on index.html
> +                    <ion-icon name="search-outline"></ion-icon>
better use classes than  id, it is a better practice

2020-09-28 16:51 UTC, javitocor commented on styles.css
> +#youtubelogo{
again, change it into classes

2020-09-29 15:12 UTC, cgcarlosg commented
Changes done

2020-09-29 15:12 UTC, cgcarlosg commented
Changes done

2020-09-29 15:12 UTC, closed without merging